### ISSUE TITLE
Failing compile on Debian 8 (fails on context.lo)

### ISSUE THREAD

**Issue by Kspen** [awslabs/aws-elasticache-cluster-client-libmemcached#3]
Any advice on how I can get this to compile?

Configuration summary for libmemcached version 1.0.8
- Installation prefix:       /usr/local
- System type:               unknown-linux-gnu
- Host CPU:                  x86_64
- C Compiler:                gcc (Debian 4.9.2-10) 4.9.2
- Assertions enabled:        yes
- Debug enabled:             no
- Warnings as failure:       yes
- SASL support:

---

$ make
....
  CXX    libhashkit/libhashkit_libhashkit_la-aes.lo
  CXX    libhashkit/libhashkit_libhashkit_la-algorithm.lo
  CXX    libhashkit/libhashkit_libhashkit_la-behavior.lo
  CXX    libhashkit/libhashkit_libhashkit_la-crc32.lo
  CXX    libhashkit/libhashkit_libhashkit_la-digest.lo
  CXX    libhashkit/libhashkit_libhashkit_la-encrypt.lo
  CXX    libhashkit/libhashkit_libhashkit_la-fnv_32.lo
  CXX    libhashkit/libhashkit_libhashkit_la-fnv_64.lo
  CXX    libhashkit/libhashkit_libhashkit_la-function.lo
  CXX    libhashkit/libhashkit_libhashkit_la-has.lo
  CXX    libhashkit/libhashkit_libhashkit_la-hashkit.lo
  CXX    libhashkit/libhashkit_libhashkit_la-jenkins.lo
  CXX    libhashkit/libhashkit_libhashkit_la-ketama.lo
  CXX    libhashkit/libhashkit_libhashkit_la-md5.lo
  CXX    libhashkit/libhashkit_libhashkit_la-murmur.lo
  CXX    libhashkit/libhashkit_libhashkit_la-one_at_a_time.lo
  CXX    libhashkit/libhashkit_libhashkit_la-rijndael.lo
  CXX    libhashkit/libhashkit_libhashkit_la-str_algorithm.lo
  CXX    libhashkit/libhashkit_libhashkit_la-strerror.lo
  CXX    libhashkit/libhashkit_libhashkit_la-string.lo
  CXX    libhashkit/libhashkit_libhashkit_la-nohsieh.lo
  CXXLD  libhashkit/libhashkit.la
  CXX    libmemcached/csl/libmemcached_libmemcached_la-context.lo
In file included from ./libmemcached/csl/context.h:41:0,
                 from libmemcached/csl/context.cc:39:
./libmemcached/csl/parser.h:124:19: error: 'Context' was not declared in this scope
 int config_parse (Context _context, yyscan_t *scanner);
                   ^
./libmemcached/csl/parser.h:124:28: error: 'context' was not declared in this scope
 int config_parse (Context *context, yyscan_t *scanner);
                            ^
./libmemcached/csl/parser.h:124:37: error: 'yyscan_t' was not declared in this scope
 int config_parse (Context *context, yyscan_t *scanner);
                                     ^
./libmemcached/csl/parser.h:124:47: error: 'scanner' was not declared in this scope
 int config_parse (Context *context, yyscan_t *scanner);
                                               ^
./libmemcached/csl/parser.h:124:54: error: expression list treated as compound expression in initializer [-fpermissive]
 int config_parse (Context *context, yyscan_t *scanner);
                                                      ^
Makefile:5237: recipe for target 'libmemcached/csl/libmemcached_libmemcached_la-context.lo' failed
make[1]: *_\* [libmemcached/csl/libmemcached_libmemcached_la-context.lo] Error 1

Makefile:2226: recipe for target 'all' failed
make: **\* [all] Error 2

Any suggestions greatly appreciated

**Comment by timtimellis** [comment]
Also fails on CentOS 7.2 with the same error.

**Comment by davidbitton** [comment]
@timtimellis ditto

**Comment by Kspen** [comment]
As stated in https://github.com/awslabs/aws-elasticache-cluster-client-libmemcached/issues/6 , this issue is resolved by using a newer version of libmemcached.

**Comment by davidbitton** [comment]
I'm not sure I understand. Aren't we supposed to build AWS's libmemcached and then this?
