### ISSUE TITLE
Please update to libmemcached 1.0.18

### ISSUE THREAD

**Issue by sodabrew** [awslabs/aws-elasticache-cluster-client-libmemcached#6]
The compilation issues reported in the open issue and open PR should be resolved by updating to a newer base version of libmemcached. The most recent is 1.0.18: https://launchpad.net/libmemcached/+download

This newer version of libmemcached is also known to fix several bugs when talking to recent memcached servers. For example, ElastiCache now offers memcached 1.4.25 and 1.4.33 and would benefit from the up-to-date client library.

**Comment by Kspen** [comment]
I forgot that was still open.  I can confirm your statements as correct.  I have referenced this issue in my comments [in issue "Failing compile on Debian 8"] and closed that issue.  Thanks for your post.

**Comment by mvanbaak** [comment]
This update is also needed to compile the current version of the aws php module for php7 (they merged upstream and it now depends on 1.0.16 or newer)

**Comment by sodabrew** [comment]
php-memcached 3.0 _requires_ libmemcached 1.0.x, but _suggests_ 1.0.16 or newer. Version 1.0.8 here will still compile and work, but with the same known bugs as prior versions. I would take heart that if they've pulled in the latest php-memcached 3.0.0, that they'll be working on the libmemcached library next.

**Comment by mvanbaak** [comment]
No, it wont. See https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-php/issues/12

**Comment by malyeyev-AMZN** [comment]
Confirming that it won't build with 1.0.8

**Comment by malyeyev-AMZN** [comment]
We are currently actively working on updating to 1.0.18

I will post any updates in this thread as soon as there is more info

**Comment by malyeyev-AMZN** [comment]
ElastiCache version of libmemcached 1.0.18 is finally available:

https://github.com/awslabs/aws-elasticache-cluster-client-libmemcached/releases/tag/v1.0.18
