### ISSUE TITLE
v1.0.18 failing unit tests on make both Ubuntu and AWS Linux

### ISSUE THREAD

**Issue by jdolinski** [awslabs/aws-elasticache-cluster-client-libmemcached#9]
Hello, I am getting errors on my unit tests when running make on Ubuntu 16. 
Example:
/home/dotcomm/step1/aws-elasticache-cluster-client-libmemcached/BUILD/../libtest/dynamic_mode.cc:60: undefined reference to `parse_memcached_configuration'

All the errors are "undefined reference". Is it compatible with Ubuntu 16?

**Comment by jdolinski** [comment]
Tested on Ubuntu 14 and getting same error. Tests are unable to resolve memcached references. Is there a prerequisite I am missing?

**Comment by jdolinski** [comment]
Confirmed v1.0.8 works as described in the [AWS documentation](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/Appendix.PHPAutoDiscoveryCompile.html#Appendix.PHPAutoDiscoveryCompile.Client) However, v1.0.18 is not working and failing unit tests for dynamic mode.

**Comment by malyeyev-AMZN** [comment]
Is this a duplicate of https://github.com/awslabs/aws-elasticache-cluster-client-libmemcached/issues/8 ?

**Comment by jdolinski** [comment]
Hello,

Yes, it is a duplicate of #8. I also believe #7 is related.

Thanks, -jim

**Comment by QuChen88** [comment]
Resolving.
